### ISSUE TITLE
Use  $XDG_CONFIG_HOME/safe instead of $HOME/.safe on Linux

### ISSUE THREAD

**Issue by b-zee** [maidsafe/safe-api#203]
To avoid pollution of the `$HOME` directory I'd recommend following the [_XDG Base Directory Specification_](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html):

>   $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

**Comment by bochaco** [comment]
Yes, it sounds good, we'll take a look at this, it seems folks started to use https://crates.io/crates/directories in vaults for using XDG.

**Comment by bochaco** [comment]
I'm planning to resolve this issue by storing the safe-cli credentials onto the project's local data folder ($XDG_DATA_HOME) rather than config, since it's more projects data than config content, I hope everyone is happy with it, @b-zee @joshuef ? 
E.g. in Linux this would go onto `~/.local/share/safe-cli/credentials`

**Comment by joshuef** [comment]
Seems like okay reasoning to me 👍

**Comment by b-zee** [comment]
Credentials sound more like configuration to me. It's definitely not 'data' to me. Thought it's a matter of interpretation and I could understand both. But, in my experience, the `.config` directory contains files that users might want to manage themselves. It's comparable with `/etc` and `/usr/local/share`.

One example I just looked at is Keybase. Keybase stores the credentials in `.config` and stores the data files (e.g. chats) in `.local/share`.

**Comment by joshuef** [comment]
The user should not really be updating these beyond the `safe auth` cli command operations (in my mind at least). These are the application's own credentials and not the user's log in details for example. ('should not' at least to my mind, but if there are compelling reasons to be managing / changing these then I'd agree that's more config-y)

**Comment by bochaco** [comment]
Yes, I was thinking along the same lines as you @joshuef , not sure if @b-zee you are still disagreeing or you were understanding that the credentials file was something else? 
This file's is obtained from the Authenticator after being authorised, so it's not a configuration file for the app and its functionality, so that's why I thought it was app's data and not app's config.

**Comment by b-zee** [comment]
I did not misunderstand. The user not updating the file outside of `safe auth` I understand; this is analogous to not mess with the Keybase files outside of Keybase.
To me, credentials form a parameter/input to the program. So it's not a 'data file' in the sense I see them being used on my system. Based on this I would say it belongs in configuration. Looking at my `.local/share` folder it contains mostly downloaded plugins, databases, logs, app data (e.g. an imported e-book), etc.

I'm not sure about this however. There is not much information that we can rely on to make a decision, so ultimately I can understand both as long as a good reason is given. It seems the line isn't very obvious between config and data files anyway!

**Comment by joshuef** [comment]
yeh, i see what you're saying @bzee. I think i'd roll with this PR on the basis that this is not _intended_ user configuration if nothing else. As you say, the line is thin, it seems but that intention seems like a good enough reason to separate it out from other 'config' we may want for the cli at a later date, eg.
