### ISSUE TITLE
`safe files sync` fails to update changed files

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe-api#271]
I uploaded an app to `safe://solid-filemanager` which worked, made some changes and rebuilt the ./build directory and then attempted to update the shared vault as follows. But I see that while new files have been uploaded and deleted files are deleted, the app does not work because although `./build/index.html` has changed it was not updated, which causes the app to fail as it tries to load the files which have been deleted. You can see from the output below that `index.html` is not update:
```
safe files sync -r ./build/ safe://solid-filemanager -u -d
FilesContainer synced up (version 1): "safe://solid-filemanager"
+  ./build/precache-manifest.af230ca88da8d9c886cd5120bbb0119a.js  safe://hbyyyydxwtwoox6s8i6kt5cdfw3ne1adqj3gyb5dq81h91k6uq19krkm43 
+  ./build/static/js/main.2c523573.chunk.js                       safe://hbyyyyn387fq7nacoya9kanp659nf9895ogd3gw34d1gxq35r4pci8rtci 
+  ./build/static/js/main.2c523573.chunk.js.map                   safe://hbyyyyd8mm1s645mys3mqdcyjzpobzwyawsaoqtsz6wqnozogptjat79tj 
-  /precache-manifest.c959321ddd7159002846116ea7c06a1b.js         safe://hbyyyydoxadadgm6cagec68gfduioti1r1m5ctcoi6trsrnofhjbn5tcc5 
-  /static/js/main.59a99085.chunk.js                              safe://hbyyyynmor3r8qiwdtafiggp5i3t7bw4iewmxehsw1fnsf3udwtg7iko17 
-  /static/js/main.59a99085.chunk.js.map                          safe://hbyyyyduim63o4jgcme7nycxxxpyr1dqa1cxpegazaxg1eoczbsb7wc8x9
```
Inspecting the container with `safe cat safe://solid-filemanager?v=0` (and v=1) you can confirm the contents have only been partially updated.

## Your Environment

I'm using the shared vault with:

- safe_auth: 0.1.0
- safe: 0.2.2
- SAFE Browser 0.15.1
- Operating System and version: Ubuntu 19.04
- Link to your project: https://github.com/theWebalyst/solid-filemanager/tree/safe-network-able

Note: you should not try to reproduce this with my project as it depends on two other modules that I've forked, but I think you should be able to reproduce it using a similar project with the SAFE CLI commands in the terminal.

**Comment by bochaco** [comment]
@theWebalyst can you please confirm which way the index.html file changed? currently the changes are recognised only if the size changed, so if this is the case it's expected to happen due to this limitation. There is also this ther issue (https://github.com/maidsafe/safe-cli/issues/135) about considering other aspects for detecting changes but they are not implemented yet.

**Comment by theWebalyst** [comment]
That's the reason, the file content has changed (referencing the newly built JS) files but the size of index.html is unchanged. This is a ReactJS project so this kind of behaviour may be common for many changes in many projects, and in other frameworks.

I guess if you can calculate the xor address in the client and compare it with the one in the FilesContainer that should be bullet proof.

**Comment by bochaco** [comment]
Yes, exactly, use the hashing to compare if the file name matches the remote one. I'll try to play around with it in the next few days to see if we can fix it.
