### ISSUE TITLE
Sign & notarize executable for macOS

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-api#311]
Otherwise users of macOS Catalina will see an error when they try to launch through terminal or dbl click
![image](https://user-images.githubusercontent.com/37112040/68468998-24018380-0211-11ea-974e-769e1a9ad159.png)

Workaround in the meantime = right click then select open. Doing this once allows the app to be opened from then on without error

**Comment by joshuef** [comment]
FYI some tips: https://stackoverflow.com/questions/55833479/do-we-need-to-notarize-frameworks-framework-dylibs-and-binaries

**Comment by joshuef** [comment]
Sample sign command: `codesign --force --deep -s <dev id key>  --options runtime --timestamp <the bin>`

This must be packaged inside a `zip` for notarize to work.

Sample notarize: `xcrun altool --notarize-app -f <bin>.zip --primary-bundle-id <bundle id, eg: com.maidsafe.safe-cli> -u "$APPLE_ID" -p "$APPLE_ID_PASSWORD"`

And checking notarize status:
`xcrun altool --notarize-info <UUID from notarize command> -u "$APPLE_ID" -p "$APPLE_ID_PASSWORD"`
