### ISSUE TITLE
Async APIs

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-api#313]
Expose all applicable async APIs as Rust native async functions

**Comment by chpio** [comment]
somewhat related to this: i think we also need a streaming based api for at least IM. The current files api works by passing in the whole file content into it, that is not going to scale well for big files. An api that takes a `futures::Stream<Item=bytes::Bytes>` would be desperately needed.

**Comment by bochaco** [comment]
Pausing this needs new quic-p2p release and updated in vault and safe_client_libs.
