### ISSUE TITLE
aws key

### ISSUE THREAD

**Issue by ErwinOlie** [maidsafe/safe-api#333]
https://github.com/maidsafe/safe-api/blob/1a7db7be75c1e7b9bb54de996c9d84ab36f51d86/.github/workflows/master.yml#L153

thanks

**Comment by m-cat** [comment]
Hi Erwin,

It would be more helpful to us if you elaborated on why you opened this issue. I'm guessing you wrote a script to detect and inform repo owners of exposed AWS secrets, but this is the public part of the AWS access details. As far as we're aware, this is not a security concern unless the secret part is also exposed.
