### ISSUE TITLE
perf: safe-cli network commands are slow even when everything on localhost

### ISSUE THREAD

**Issue by dan-da** [maidsafe/safe-api#337]
This may be caused due to debug info and not an issue for release builds, but I figured I'd create an issue for discussion if we can do better, or maybe it is just an issue in my environment somehow.

I have everything running locally (safe_vault, safe_authd, safe-cli) and so I would expect that commands should return in fractions of a second.  Instead, I am consistently seeing more like 5 seconds.

Here are two examples, calling safe files put and safe dog:

```
$ time safe files put subcommands/
FilesContainer created at: "safe://hnyynyzb9bmpd37rikyiduhbf85nx3oz9pkf61fzqorugn7jy1amwo48hhbnc"
+  subcommands/auth.rs       safe://hbyyyydtf76dc3dfqwuf93fp1fg6oyfbmekjj4ip754i78f5qfhjekpm8w 
+  subcommands/cat.rs        safe://hbyyyyns97fgrrtb4e84tjxcy95iz5zyo3qtn186fioucdkjfpm8t3851r 
+  subcommands/container.rs  safe://hbyyyydo1obptnhhg8ercmh47fu5cswj9esy36pf18fsjyksgkrbfe1h4x 
+  subcommands/dog.rs        safe://hbyyyynmprw951arodzf5npt498wgbgoxwpep7uuxbd3hibj3i4ddoweoa 
+  subcommands/fake_auth.rs  safe://hbyyyydpzubf3bw38sri9xstm7ietoh31ybi7u8qu7cfief3ugnnew6j6c 
+  subcommands/files.rs      safe://hbyyyynrqk7gq4yzuuegfxufrm5oe6ooeqb45ugph4nnipxdxyfwthy9of 
+  subcommands/helpers.rs    safe://hbyyyyd7bwch4ggbxjj95n6cbg9ct9nxi9qjgcxgo4aariuwdf3mfkn1zf 
+  subcommands/keys.rs       safe://hbyyyyn6wafae79gxcwmhikxqc1pbax8iphyd83yb914tcbfanokhgpta1 
+  subcommands/mod.rs        safe://hbyyyyd5pznudcghrd815zg675i95njg49bc91zanugudea7eiaxbrbiky 
+  subcommands/nrs.rs        safe://hbyyyynimmrthxwgq4yn11ks8ia6ioxbau37sefhcepa5spwj1e8zw8guc 
+  subcommands/safe_id.rs    safe://hbyyyydoxg48gaxtrajza83taob67fo9zt7z3iwc3oh13pfoou7y91nicb 
+  subcommands/update.rs     safe://hbyyyydncg5c6y339k4i7uxmso83i9bnx1sih5eizwzfwyyhc3bhed3o6e 
+  subcommands/wallet.rs     safe://hbyyyyd3immxnkazgzm1e79cpd6a8bw9yy7i5hr8akcks51ipzy7y1rumk 

real    0m4.993s
user    0m4.459s
sys     0m0.520s
```

```
$ time safe dog safe://hnyynyzb9bmpd37rikyiduhbf85nx3oz9pkf61fzqorugn7jy1amwo48hhbnc
Native data type: PublishedSeqAppendOnlyData
Version: 0
Type tag: 1100
XOR name: 0xc3f0ada3cf495502a39f0253ec4fcc2ff6a8be916ee812661752096174868fce
XOR-URL: safe://hnyynyzb9bmpd37rikyiduhbf85nx3oz9pkf61fzqorugn7jy1amwo48hhbnc

real    0m5.176s
user    0m4.455s
sys     0m0.720s
```

Upon further testing, I notice that simply calling safe --help takes 5 secs, eg:

```
$ time safe --help > /dev/null

real    0m4.943s
user    0m4.099s
sys     0m0.844s
```

So that makes me think that somehow just bootstrapping the rust executable is very heavy.   ls -lh shows it is 232Mb, so perhaps that is the cause.

What kind of times do other see for debug binaries?   release binaries?   Is this a common rust issue?

**Comment by dan-da** [comment]
update, it seems to come and go.   Eg, I killed a couple processes using some CPU, and then non-network commands were very fast:

```
$ time safe --help
...
real    0m0.019s
user    0m0.009s
sys     0m0.009s

$ time safe dog safe://hnyynyzb9bmpd37rikyiduhbf85nx3oz9pkf61fzqorugn7jy1amwo48hhbnc
[2019-11-23T02:43:54Z ERROR safe] safe-cli error: [Error] ContentNotFound - No FilesContainer found at this address

real    0m0.011s
user    0m0.005s
sys     0m0.005s
```

but now a minute later they are back to being slow.  I thought maybe there is some swapping going on, but I killed some memory hogs, verified 1.7 Gigs free with 'free -h' and I still am getting 5 sec exec time for safe --help.

cpu is 95% idle before executing, and heavily used by 'safe' during the 5 secs.

**Comment by dan-da** [comment]
ok, so this morning the commands have sped up again, through no intentional act of mine.   eg *safe --help* execs in 0.019 secs, and even the networked commands are no longer taking ~5 secs.

However, they are still slower than I would expect with everything running locally, which is why I was originally opening this issue.   examples:

```
$ time safe files put clippy.sh 
FilesContainer created at: "safe://hnyynywia67bqds6hfn31z7j5m5fhpdt466fqqnupae69m9b7czqpefksrbnc"
+  clippy.sh  safe://hbkycyd1r7hid96ykrdfam4f7pzrzm6h5tfpyc9hd9shsapyrtay1u5gms 

real    0m2.844s
user    0m0.870s
sys     0m0.032s
```
```
$ time safe dog clippy.sh 
[2019-11-23T21:08:39Z ERROR safe] safe-cli error: [Error] ContentNotFound - Content not found at clippy.sh

real    0m0.821s
user    0m0.317s
sys     0m0.004s
```

```
$ time safe dog "safe://hnyynywia67bqds6hfn31z7j5m5fhpdt466fqqnupae69m9b7czqpefksrbnc"
Native data type: PublishedSeqAppendOnlyData
Version: 0
Type tag: 1100
XOR name: 0x2b8f742e1dbdc28b32bf53b5ecbc68e3af78ae70a6dc23df5fc3d65dcd415562
XOR-URL: safe://hnyynywia67bqds6hfn31z7j5m5fhpdt466fqqnupae69m9b7czqpefksrbnc

real    0m0.858s
user    0m0.296s
sys     0m0.016s
```

So the *files put* (for a 42 byte file) took nearly 3 secs and *dog* takes nearly 1 sec.  Shouldn't these be under 0.1 sec?

**Comment by bochaco** [comment]
I guess this is more to be related to how the vault handles all these operations, and what could be causing those delays sometimes in your environment. I'm not sure if there are already analysis made on the performance of the vault and filesystem access from it.

**Comment by iancoleman** [comment]
I tried to reproduce this but could not.

This is my environment

```text

$ rustup show
Default host: x86_64-unknown-linux-gnu
active toolchain
----------------
stable-x86_64-unknown-linux-gnu (default)
rustc 1.38.0 (625451e37 2019-09-23)

All compiled with --release flag

$ ./safe_vault --version; git rev-parse HEAD
safe-vault 0.19.2
61c20dd8455fe26dd4662670d7e662ed68ff7766

$ ./safe_auth --version; git rev-parse HEAD
safe_auth 0.3.0
465e29ff705ac850dfd35b846ae1ad577cb8ec75

$ ./safe --version; git rev-parse HEAD
safe-cli 0.5.0
d381a9ddcc1b304b37903163476f07b0ed5e097c
```

Steps attempted to reproduce:

* Run vault
* Run `safe_auth` to create account then run daemon
    * `$ ./safe_auth --test-coins`
    * `$ ./safe_auth --allow-all-auth --daemon 41805`
* Upload files
    * `$ ./safe auth`
    * `$ ./safe files put ~/parsec/ --recursive`
    * `$ time ./safe cat safe://hbkydydi77gfemrd6mfkbdwzbb8r3sw9cdyc85qg3aef7rbwi3yjmiymrf`
    * repeat cat

Every cat command ran fast, never less than 0.2s

So ... maybe can you confirm your versions and environment first?

Then painful though it is, maybe try to reproduce the issue with environment variable `RUST_LOG=trace` and see if the trace has any further info.

eg

```text
$ RUST_LOG=trace ./safe cat safe://hbkyd...
```

**Comment by bochaco** [comment]
I'm quite positive @dan-da is using safe-authd and the vault from `vNext` branch, so it seems this issue was introduced post vault v0.19.2

**Comment by iancoleman** [comment]
Thanks @bochaco.

I ran the test on vNext/master branches and still could not reproduce. All cat commands ran in around 25ms.

---

Some notes for others who may be interested in trying to reproduce this.

Details of environment using master branch of `safe-api` and vNext branch of `safe_vault`:

```text
rustc 1.38.0 (625451e37 2019-09-23)

all compiled with --release

safe-api/target/release $ ./safe --version; git rev-parse HEAD
safe-cli 0.5.0
02119c3ab495a5c7cbc852ae0ed80bfbf81a1dee

safe_vault/target/release $ ./safe_vault --version; git rev-parse HEAD
safe-vault 0.19.2
0bc7e2d89b8b8c3c0250348e214ed700e7071a6a
```

Process to run test (from [the cli docs](https://github.com/maidsafe/safe-api/blob/02119c3ab495a5c7cbc852ae0ed80bfbf81a1dee/safe-cli/README.md#using-the-cli)).

```text
$ ./safe_vault --first
```

```text
$ ./safe-authd start
$ ./safe auth create-acc --test-coins
$ ./safe auth login
$ ./safe auth
(open new terminal)
$ ./safe auth reqs
$ ./safe auth allow <id>
(close new terminal)
$ ./safe files put ~/parsec/ --recursive
$ ./safe cat safe://hbyyyyd8...
```

Gotchas I encountered:

**vault flag needed**

Must start vault with `--first` flag. Maybe need revision to docs https://github.com/maidsafe/safe-api/blob/master/safe-cli/README.md#vault-must-be-running. Maybe also change log level for bootstrap failure, the following log lines do not show up unless using environment variable `RUST_LOG=trace` but are pretty important messages and should not depend on the presence of the environment variable. With no environment variable the vault looks like it's running correctly when it isn't.
```text
INFO 2019-11-29T22:32:00Z [/home/ian/.cargo/git/checkouts/routing-616e72cf40f12bc0/58e4eb5/src/states/bootstrapping_peer.rs:301] BootstrappingPeer(5be327..) Failed to bootstrap. Terminating.
DEBUG 2019-11-29T22:32:00Z [/home/ian/.cargo/git/checkouts/routing-616e72cf40f12bc0/58e4eb5/src/state_machine.rs:413] State::BootstrappingPeer(5be327..) Terminating state machine
```

**safe auth explanation**

Need in cli logs to explain how `safe auth` requires you to open a second window and do `safe auth reqs` and `safe auth allow <id>`. It's in the docs but the app should be 'standalone' self documenting and not require external docs. I guess maybe this workflow in the future will have authd respond with the reqid and allow user to accept it in a prompt from `safe auth` so it's all in one simple command...? The log for this process is:
```text
$ ./safe auth
Authorising CLI application...
<I think some extra info here would be very helpful>
[2019-11-29T22:10:13Z ERROR jsonrpc_quic::quic_client] Connection lost: timed out
[2019-11-29T22:10:13Z ERROR safe] safe-cli error: Application authorisation failed: [Error] AuthdClientError - Failed to read response: connection closed: timed out
```

**Comment by bochaco** [comment]
yes @iancoleman I think it's a good idea to add some more info in that particular case, I'll see if i add something in my next WIP PR.

Using the interactive shell you get the notification of the auth req, so you can then simply call allow form it. It's not possible yet to have the prompt in the interactive shell for say "y/N" just due to some missing piece in the implementation of the safe-api, but it's in the todo list.

**Comment by dan-da** [comment]
> I ran the test on vNext/master branches and still could not reproduce. All cat commands ran in around 25ms.

@iancoleman 25 ms real or cpu?    Can you post output of *time safe dog &lt;url>*?   Here's mine.

```
$ time safe dog safe://hbkycyn4ucn3tucsbgf7rxb41bfnowoecsqzbsiwhpwqmcmuw3uh8dzyre
...
real    0m0.789s
user    0m0.282s
sys     0m0.017s
```

**Comment by iancoleman** [comment]
Laptop

```text
$ time ./safe dog safe://hbhydynq3rpu9qy6qqsakmr93qx7bstypuhgx8ohg7bqgz7u7g6wo6677i
Native data type: ImmutableData (published)
XOR name: 0x3b246cfee079ceb614b27f2e7f436881b3e19e7870dd0b8d7ecfa6f521ef77b5
XOR-URL: safe://hbhydynq3rpu9qy6qqsakmr93qx7bstypuhgx8ohg7bqgz7u7g6wo6677i
Media type: text/plain

real	0m0.020s
user	0m0.007s
sys	0m0.006s

$ cat /proc/cpuinfo | grep "model name" | head -n 1
model name	: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

$ uname -a
Linux ian-laptop 5.0.0-36-generic #39-Ubuntu SMP Tue Nov 12 09:46:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ rustc --version
rustc 1.39.0 (4560ea788 2019-11-04)
```

Desktop

```text
$ time ./safe dog safe://hbhydynq3rpu9qy6qqsakmr93qx7bstypuhgx8ohg7bqgz7u7g6wo6677i
Native data type: ImmutableData (published)
XOR name: 0x3b246cfee079ceb614b27f2e7f436881b3e19e7870dd0b8d7ecfa6f521ef77b5
XOR-URL: safe://hbhydynq3rpu9qy6qqsakmr93qx7bstypuhgx8ohg7bqgz7u7g6wo6677i
Media type: text/plain

real	0m0.020s
user	0m0.005s
sys	0m0.009s

$ cat /proc/cpuinfo | grep "model name" | head -n 1
model name	: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

$ uname -a
Linux ian-desktop 5.0.0-36-generic #39-Ubuntu SMP Tue Nov 12 09:46:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ rustc --version
rustc 1.39.0 (4560ea788 2019-11-04)
```

**Comment by dan-da** [comment]
ok, well those numbers are convincing to me.

I am running a debug build of both safe_vault safe-cli, so I guess it is one or the other or both of them.

@iancoleman if you happen to have debug builds also and can post those numbers, that would be good to have an apples-to-apples comparison.

Anyway, I am closing this as it does not seem to affect release builds.

**Comment by iancoleman** [comment]
> if you happen to have debug builds also and can post those numbers

Repeat tests of debug builds for vault and api gave range of 350ms to 700ms, mostly around 400ms.

```text
$ time ./target/debug/safe dog safe://hbhydynq3rpu9qy6qqsakmr93qx7bstypuhgx8ohg7bqgz7u7g6wo6677i
Native data type: ImmutableData (published)
XOR name: 0x3b246cfee079ceb614b27f2e7f436881b3e19e7870dd0b8d7ecfa6f521ef77b5
XOR-URL: safe://hbhydynq3rpu9qy6qqsakmr93qx7bstypuhgx8ohg7bqgz7u7g6wo6677i
Media type: text/plain

real	0m0.461s
user	0m0.201s
sys	0m0.000s
```
Have you tried release builds and seen if that fixes it? `cargo build --release`

I think it's maybe too early to close the bug. I simply wanted to reproduce it but my experience is only one datapoint so the bug seems to me still worth pursuing.
