### ISSUE TITLE
Add support for more shells - not receiving full feedback from some `safe auth xxx` commands

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-api#406]
I'm working on macOS 10.15.2 and using the `fish` shell 🐟 
When I run `./safe auth login` I do not receive feedback on whether my login attempt was successful or not.
```
./safe auth login 
Passphrase:
Password:
Sending login action request to authd...
```
Switching to standard `bash` shell resolves this issue.
There may be more commands and more shells which are affected.

**Comment by bochaco** [comment]
Just for reference, and to consider when testing such an improvement, there has been similar issues with MinGW: https://forum.safedev.org/t/problem-with-latest-safe-authenticator-cli/2529/57

Also, for ref, the issue is in the crate we use for prompting the user: https://crates.io/crates/rpassword
