### ISSUE TITLE
authd on Windows - No safe-authd log files/folder created

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-api#441]
Windows 10
authd v0.0.5

authd log folder location should be `C:\Users\<user>\.safe\authd\logs\`
However this folder is not created when I run v0.0.5 authd on a Windows VM. A forum member has reported the same issue [here](https://safenetforum.org/t/support-issues-with-baby-fleming-version-1-vaults-phase-2a-single-section-network/31234/14?u=stephenc)

**Comment by bochaco** [comment]
This is a limitation currently in authd for Windows, I didn’t find yet the way to log from a Windows service, so I confirm the logs are not output as in other platforms. I propose to refactor authd for Windows and launch it in the background just like we do for vaults in Baby Fleming and don’t set it up as a Windows service. This will allow us to send the logs to the same location as it’s done on Linux and Mac, and also this will remove the need of having admin perms for authd commands on Windows.
