### ISSUE TITLE
`safe auth update` fails when not located in `~/.safe/`

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe-api#496]
### Context
Following the instructions to update to safe CLI from [SAFE Network Dev Update - March 26, 2020](https://safenetforum.org/t/safe-network-dev-update-march-26-2020/31360?u=happybeing):

> If you have used the CLI before, then you should update it by running:
> `$ safe update`
>
>You should also then update the Authenticator daemon:
>`$ safe auth update`

### Behaviour
Having earlier downloaded `safe` to `~/bin/safe` which is on my path I updated as instructed above. Using `safe update` works fine, but then:
```
$ safe auth update
[2020-03-31T10:54:59Z ERROR safe] safe-cli error: [Error] AuthdClientError - Failed to execute authd from '/home/mrh/.safe/authd/safe-authd': No such file or directory (os error 2)
```
Looking in `~/bin` shows that `safe` was updated but obviously the other products are not being found there:
```
$ ls -l ~/bin/safe*
-rwxr-xr-x 1 mrh mrh  26824936 Mar 26 15:12 /home/mrh/bin/safe
-rwxr-xr-x 1 mrh mrh  17447520 Feb 24 21:10 /home/mrh/bin/safe0.2.2
-rwxr-xr-x 1 mrh mrh  13560224 Feb 24 21:10 /home/mrh/bin/safe_auth
-rwxr-xr-x 1 mrh mrh  19023728 Feb 24 21:10 /home/mrh/bin/safe_auth0.2.0
-rwxr-xr-x 1 mrh mrh 112504460 Feb 24 21:10 /home/mrh/bin/safe-browser.AppImage
-rwxr-xr-x 1 mrh mrh  12239576 Feb 24 21:10 /home/mrh/bin/safe_vault
-rwxr-xr-x 1 mrh mrh  18526096 Feb 24 21:10 /home/mrh/bin/safe_vault0.19.0
```

So I guess we need to only install `safe` and its buddies in `~/.safe/`. Ideally this should be enforced, and documented in the meantime.

### Workaround:
Move everything to `~/.safe/` and add it to the path.

### Environment
- Ubuntu 19 (.10 I think)

### UPDATE
PS I'm guessing I hit this because I skipped the local single section release. I didn't have a `~/.safe` so have gone back to the install script to try and fix this.

**Comment by theWebalyst** [comment]
I now needed to do the following to install the vault and authenticator:
```
safe vault install
safe auth install
```
Then...
```
safe networks add shared-section https://safe-vault-config.s3.eu-west-2.amazonaws.com/shared-section/vault_connection_info.config
```
But oops... 
```
safe networks switch shared-section
Switching to 'shared-section' network...
Fetching 'shared-section' network connection information from 'https://safe-vault-config.s3.eu-west-2.amazonaws.com/shared-section/vault_connection_info.config' ...
[2020-03-31T11:31:09Z ERROR safe] safe-cli error: Unable to write config in /home/mrh/.config/safe_vault/vault_connection_info.config: No such file or directory (os error 2)

```

The last error is fixed by `mkdir ~/.config/safe_vault` so maybe the command should check for its existence?

**Comment by bochaco** [comment]
The first error is because you didn't have authd installed in the default location `~/.safe/authd`:
```
$ safe auth update
[2020-03-31T10:54:59Z ERROR safe] safe-cli error: [Error] AuthdClientError - Failed to execute authd from '/home/mrh/.safe/authd/safe-authd': No such file or directory (os error 2)
```
I'll make sure the path for valt config is created if it doens't exist when doing `networks switch`.
