### ISSUE TITLE
enhancement: safe dog view on previous NRS Map versions

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe-api#544]
Might be useful for dog to have option to see previous version detail of NRS Map

safe://dpb
was v=0 SafeKey
now v=1 PublishedSeqAppendOnlyData

but safe dog safe://dpb looks to only have option now to show v=1

**Comment by bochaco** [comment]
Not sure I understand, but you can always set a version in the URL you are running dog against, e.g. `safe dog safe://dbp?v=0`

**Comment by davidpbrown** [comment]
thanks!.. was looking to flags on the command itself
