### ISSUE TITLE
safe cat not acknowledging alias and then misrepresenting subdirectories listings

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe-api#561]
I wonder cat is not properly representing the nature of files uploaded as subdirectory.

So, safe://the.odyssey was uploaded as the subfolder /the/ with no content at the top level and the NRS alias set to see safe://the.odyssey as that.

Looking at the output of cat, it is not apparent that it is not safe://odyssey with those files listed as if the were directly at the top of domain.
This creates confusion of what is top level and what is not and a mismatch on what's expected, which is a nuisance if perspective is from xorurls.

This on safe-cli 0.12.0 but expecting it's not a difference with the newer changes.
```
$ safe dog safe://odyssey
Native data type: PublishedSeqAppendOnlyData
Version: 0
Type tag: 1100
XOR name: 0x0d40d8d670dfd81c93c445c008adb8804603d4cc715de43b4615904ece3f8e40
XOR-URL: safe://hnyynywgwbsgsqdx7o8ruatnhynfpznyrcy6w3tai53b5eak3yusq868rybnc?v=0

Resolved using NRS Map:
PublicName: "odyssey"
Container XOR-URL: safe://hnyydywpz84tasutggsw8aofhzbf7p4u6x93ukyu9iw4tyimw63ph9941hbqh
Native data type: PublishedSeqAppendOnlyData
Type tag: 1500
XOR name: 0x1b73ea38b4e2635a87c40bcb84bd6ea7e7ff335027fad35105574f65bcfff52e
Version: 0
+------------------+----------------------+----------------------+--------------------------------------------------------------------------+
| NRS name/subname | Created              | Modified             | Link                                                                     |
+------------------+----------------------+----------------------+--------------------------------------------------------------------------+
| odyssey          |                      |                      | Alias to subname 'the'                                                   |
+------------------+----------------------+----------------------+--------------------------------------------------------------------------+
| the.odyssey      | 2020-04-21T16:28:23Z | 2020-04-21T16:28:23Z | safe://hnyynywgwbsgsqdx7o8ruatnhynfpznyrcy6w3tai53b5eak3yusq868rybnc?v=0 |
+------------------+----------------------+----------------------+--------------------------------------------------------------------------+
$ safe cat safe://odyssey
Files of FilesContainer (version 0) at "safe://odyssey":
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| Name        | Size    | Created              | Modified             | Link                                                              |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| /index.html | 437     | 2020-04-21T16:27:32Z | 2020-04-21T16:27:32Z | safe://hbhybydugiiy4c3jajci9dnpu9xfx8fozujquzj7tukk8zwoaex8p911qj |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| /style.css  | 101     | 2020-04-21T16:27:32Z | 2020-04-21T16:27:32Z | safe://hbhyyyn5ysy1ehowix3gz38ydr63z1fd8583f93wi11o3674pm5d95yfn5 |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| /tma.gif    | 1363714 | 2020-04-21T16:27:32Z | 2020-04-21T16:27:32Z | safe://hbwyyongrpdwwqxjebrqgx57qrkijgsg6o4z8opg7gbduk79mxuooeehkt |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
$ safe cat safe://hnyynywgwbsgsqdx7o8ruatnhynfpznyrcy6w3tai53b5eak3yusq868rybnc?v=0
Files of FilesContainer (version 0) at "safe://hnyynywgwbsgsqdx7o8ruatnhynfpznyrcy6w3tai53b5eak3yusq868rybnc?v=0":
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| Name        | Size    | Created              | Modified             | Link                                                              |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| /index.html | 437     | 2020-04-21T16:27:32Z | 2020-04-21T16:27:32Z | safe://hbhybydugiiy4c3jajci9dnpu9xfx8fozujquzj7tukk8zwoaex8p911qj |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| /style.css  | 101     | 2020-04-21T16:27:32Z | 2020-04-21T16:27:32Z | safe://hbhyyyn5ysy1ehowix3gz38ydr63z1fd8583f93wi11o3674pm5d95yfn5 |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| /tma.gif    | 1363714 | 2020-04-21T16:27:32Z | 2020-04-21T16:27:32Z | safe://hbwyyongrpdwwqxjebrqgx57qrkijgsg6o4z8opg7gbduk79mxuooeehkt |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
```

**Comment by dan-da** [comment]
> So, safe://the.odyssey was uploaded as the subfolder /the/ with no content at the top level and the NRS alias set to see safe://the.odyssey as that.

Can you please post the full set of commands to reproduce, eg: `files put`, `nrs create`, `cat`?

**Comment by davidpbrown** [comment]
No surprises.. as below, just nrs create subdir.domain on the back of uploading the files for that.
safe cat perhaps just needs to note either that the endpoint of safe://odyssey2 an alias or that it goes one step beyond and suggests ALSO then content that would be returned from than endpoint.

below the abc and then ```safe cat safe://odyssey2``` not doing what  ```safe dog safe://odyssey2``` does to reflect the reality of structure.

```
$ safe files put --recursive ./the/
FilesContainer created at: "safe://hnyynyst3n48ex6copsx191u9t1d11zxo45zewdi1knx7r63xxop8pcymybnc"
+  ./the/index.html  safe://hbhybydugiiy4c3jajci9dnpu9xfx8fozujquzj7tukk8zwoaex8p911qj 
+  ./the/style.css   safe://hbhyyyn5ysy1ehowix3gz38ydr63z1fd8583f93wi11o3674pm5d95yfn5 
+  ./the/tma.gif     safe://hbwyyongrpdwwqxjebrqgx57qrkijgsg6o4z8opg7gbduk79mxuooeehkt 
$ safe nrs create the.odyssey2 --link safe://hnyynyst3n48ex6copsx191u9t1d11zxo45zewdi1knx7r63xxop8pcymybnc?v=0
New NRS Map for "safe://the.odyssey2" created at: "safe://hnyydywue37wrfj7jaeptg8m3fzw9w7u563fsn8w189pb53j3jowrc336kbqh"
+  the.odyssey2  safe://hnyynyst3n48ex6copsx191u9t1d11zxo45zewdi1knx7r63xxop8pcymybnc?v=0 
$ safe dog safe://the.odyssey2
Native data type: PublishedSeqAppendOnlyData
Version: 0
Type tag: 1100
XOR name: 0xa39168e87f9906d9f2fca7f8c87295df0d6ee8a0eb2509fd27b2f7c1a76b00b0
XOR-URL: safe://hnyynyst3n48ex6copsx191u9t1d11zxo45zewdi1knx7r63xxop8pcymybnc?v=0

Resolved using NRS Map:
PublicName: "odyssey2"
Container XOR-URL: safe://the.hnyydywue37wrfj7jaeptg8m3fzw9w7u563fsn8w189pb53j3jowrc336kbqh
Native data type: PublishedSeqAppendOnlyData
Type tag: 1500
XOR name: 0x268cf6842a7a9c21b131d792de9fa767bf64b611e923fda1de5394c2846673e5
Version: 0
+------------------+----------------------+----------------------+--------------------------------------------------------------------------+
| NRS name/subname | Created              | Modified             | Link                                                                     |
+------------------+----------------------+----------------------+--------------------------------------------------------------------------+
| odyssey2         |                      |                      | Alias to subname 'the'                                                   |
+------------------+----------------------+----------------------+--------------------------------------------------------------------------+
| the.odyssey2     | 2020-05-24T15:19:19Z | 2020-05-24T15:19:19Z | safe://hnyynyst3n48ex6copsx191u9t1d11zxo45zewdi1knx7r63xxop8pcymybnc?v=0 |
+------------------+----------------------+----------------------+--------------------------------------------------------------------------+
$ safe cat safe://the.odyssey2
Files of FilesContainer (version 0) at "safe://the.odyssey2":
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| Name        | Size    | Created              | Modified             | Link                                                              |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| /index.html | 437     | 2020-05-24T15:18:49Z | 2020-05-24T15:18:49Z | safe://hbhybydugiiy4c3jajci9dnpu9xfx8fozujquzj7tukk8zwoaex8p911qj |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| /style.css  | 101     | 2020-05-24T15:18:49Z | 2020-05-24T15:18:49Z | safe://hbhyyyn5ysy1ehowix3gz38ydr63z1fd8583f93wi11o3674pm5d95yfn5 |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| /tma.gif    | 1363714 | 2020-05-24T15:18:49Z | 2020-05-24T15:18:49Z | safe://hbwyyongrpdwwqxjebrqgx57qrkijgsg6o4z8opg7gbduk79mxuooeehkt |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
```
so safe cat is
```
$ safe cat safe://odyssey2
Files of FilesContainer (version 0) at "safe://odyssey2":
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| Name        | Size    | Created              | Modified             | Link                                                              |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| /index.html | 437     | 2020-05-24T15:18:49Z | 2020-05-24T15:18:49Z | safe://hbhybydugiiy4c3jajci9dnpu9xfx8fozujquzj7tukk8zwoaex8p911qj |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| /style.css  | 101     | 2020-05-24T15:18:49Z | 2020-05-24T15:18:49Z | safe://hbhyyyn5ysy1ehowix3gz38ydr63z1fd8583f93wi11o3674pm5d95yfn5 |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
| /tma.gif    | 1363714 | 2020-05-24T15:18:49Z | 2020-05-24T15:18:49Z | safe://hbwyyongrpdwwqxjebrqgx57qrkijgsg6o4z8opg7gbduk79mxuooeehkt |
+-------------+---------+----------------------+----------------------+-------------------------------------------------------------------+
```

**Comment by bochaco** [comment]
> safe://the.odyssey was uploaded as the subfolder /the/ with no content at the top level

@davidpbrown if I get you right, you are expecting the `the` to be considered/taken as a subfolder in the FilesContainer, but that's not correct, that's just a subname of the NRS name you are creating, and because you didn't create the NRS name `odyssey` beforehand, then `safe://odyssey` is made an alias to `safe://the.odyssey` you explicitly created.

**Comment by davidpbrown** [comment]
I'm expecting the common perception of domain names to follow. Even there you're suggesting that I'm expecting "the" as subfolder but it's just a subname.. but I'm expecting those to be one and the same.

If you're suggesting that safe://odyssey doesn't exist because safe://the.odyssey does, that's novel. I wonder what will occur when safe://odyssey is created on the back of an empty folder and then subname=subfolder added as safe://the.odyssey - will those behave the same?..

I can't see the advantage of not considering subname=subfolder.

Also, safe dog does acknowledge the alias is there.. safe cat is bouncing off the alias onto the subname.. so, that it's not makes the two domains appear identical.. which I get they are in a real sense on the network but the oddity is that the reason subname exist is to reflect structure.

Issue just reflects the normal expectation.. so, can resolve in eitherway but the usability that mirrors unSAFE and normal file folder structures on filesystems, seems to me the better option in handling subnames.

**Comment by davidpbrown** [comment]
The other way to frame this is that xors reflect the way you talk and domain/subdomains is the first level of abstraction back into the real world.. of the source files and folders as those are uploaded. There's a slight risk, which I guess could become an issue in places, of pulling back something different than was uploaded.

btw I consider this minor atm.. don't mind if it stays a problem.

**Comment by bochaco** [comment]
> If you're suggesting that safe://odyssey doesn't exist because safe://the.odyssey does

No, what I said is that because you need the odyssey to exist on the network before you can add subnames to it, so the APIs do this for you when you create a subname, creating both the name and subname, having the name to be linked to the same location you linked the subname.

Subnames (or subdomains in clearnet) are not the same as subfolder, a subname is a way to have links to different places than the link you have in the NRS name. The NRS container doesn't have subfolders, it only contains the link for the NRS name and its subnames.

Then, if an NRS name/subname is linked to a FilesContainer, an a path is provided in the URL, it will be resolved against the path in the FilesContainer.

**Comment by davidpbrown** [comment]
> The NRS container doesn't have subfolders, it only contains the links for the NRS name and its subnames.

I might be struggling with this because there are so few sites with any depth atm but if you take ```safe cat safe://maidsafe/theme``` that lists just as expected and as if theme was a subfolder. 

That is not looking like a pointer to an entirely different dataset.

What you've suggested above reads as if you could get a domain tempting that safe://domain/subfolder/file exists but looking to safe cat safe://domain/subfolder would not necessarily see that because it could be a "different place".

If you can link subnames to different locations and not see those reflected in the domain list of files, how are users not going to get confused?.. surely there is one coherent file listing that is holding structure that reflects the whole domain and expects the subname acknowledged as per OP. Otherwise finding files surely will become more complex that needs be..

Do we have to check every subname as if it is its own domain??

**Comment by bochaco** [comment]
> if you take safe cat safe://maidsafe/theme that lists just as expected and as if theme was a subfolder.
> That is not looking like a pointer to an entirely different dataset.

That is a subolder in the FilesContainer linked from NRS name maidsafe, so in that case maidsafe is resolved to an NRS container, from there it finds a link to a FilesContainer which has a `/theme` subfolder and that's how it's resolved. That is different from something like safe://theme.maidsafe whre theme is a subname rather than a path like in safe://maidsafe/theme.

> What you've suggested above reads as if you could get a domain tempting that safe://domain/subfolder/file exists but looking to safe cat safe://domain/subfolder would not necessarily see that because it could be a "different place".

if safe://domain/subfolder/file exists, then the FilesContainer linked from `safe://domain` has a file `/subfolder/file`, and `cat safe://domain/subfolder` should show you that file in the list.

> If you can link subnames to different locations and not see those reflected in the domain list of files, how are users not going to get confused?

NRS names and subnames are just links, it's just a way to map human readable names to XOR-URLs. They are a way to have a human readable name linked to content, the linked content can be of any supported type, not just FilesContainers, but Wallets, other NRS containers, SafeKeys, ImmutableData files, etc.
You can see the list of subnames an NRS container has with the dog command, e.g.:
```
$ safe dog safe://myname

== URL resolution step 1 ==
Resolved from: safe://myname
= NRS Map Container =
PublicName: "myname"
XOR-URL: safe://hnyydywjkpxszgf4q6xbdog5uc8z5df4p11jz5jdjd3h7fparjjhpp38mhbqh
Version: 2
Type tag: 1500
XOR name: 0x12a6bed73174ef3c2381b7361efb1974d94937da4691e79d2b7044a78d6e4ebe
Native data type: PublishedSeqAppendOnlyData
+-------------------------+----------------------+----------------------+-----------------------------------------------------------------------------------------------------+
| NRS name/subname        | Created              | Modified             | Link                                                                                                |
+-------------------------+----------------------+----------------------+-----------------------------------------------------------------------------------------------------+
| myname                  | 2020-05-24T17:39:21Z | 2020-05-24T17:39:21Z | safe://hnyynyiytmdhcpquxfbez78zsdkwaarc9g8i7j7ucknqr7gadwmdrkjryqbnc?v=0                            |
+-------------------------+----------------------+----------------------+-----------------------------------------------------------------------------------------------------+
| subname1.myname         | 2020-05-24T17:39:50Z | 2020-05-24T17:39:50Z | safe://hnyynyiytmdhcpquxfbez78zsdkwaarc9g8i7j7ucknqr7gadwmdrkjryqbnc/testdata?v=0                   |
+-------------------------+----------------------+----------------------+-----------------------------------------------------------------------------------------------------+
| subsub1.subname1.myname | 2020-05-24T17:40:15Z | 2020-05-24T17:40:15Z | safe://hnyynyiytmdhcpquxfbez78zsdkwaarc9g8i7j7ucknqr7gadwmdrkjryqbnc/testdata/subfolder/sub2.md?v=0 |
+-------------------------+----------------------+----------------------+-----------------------------------------------------------------------------------------------------+

== URL resolution step 2 ==
Resolved from: safe://hnyynyiytmdhcpquxfbez78zsdkwaarc9g8i7j7ucknqr7gadwmdrkjryqbnc?v=0
= FilesContainer =
XOR-URL: safe://hnyynyiytmdhcpquxfbez78zsdkwaarc9g8i7j7ucknqr7gadwmdrkjryqbnc?v=0
Version: 0
Type tag: 1100
XOR name: 0x41158f8c6ba6f28517e9ef61aa98c119f31ebd4f66c509c4e9b03a2c64524807
Native data type: PublishedSeqAppendOnlyData
```

**Comment by davidpbrown** [comment]
Thanks that's clearer.
