### ISSUE TITLE
Files cmd: support copying remote folder to local path

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-api#74]
E.g.: `safe files cp safe://<XOR-URL> ./localfolder --recursive`

**Comment by theWebalyst** [comment]
Is this the same as `safe files sync -r safe://<xor> <directory>` **from** safe to local (without --delete) (issue #512)?

**Comment by dan-da** [comment]
@bochaco correct me if I'm wrong, but I think this what became `safe files get` and can be closed now.

**Comment by bochaco** [comment]
> I think this what became safe files get and can be closed now.

Yes, correct, closing it now.
