### ISSUE TITLE
Publish lib API as a crate for consumption from Rust client applications

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-api#76]

**Comment by bochaco** [comment]
Already done: https://crates.io/crates/safe-api

**Comment by loziniak** [comment]
Is it possible that [docs.rs api reference](https://docs.rs/crate/safe-api/0.5.0) would also generate?

**Comment by bochaco** [comment]
Yes, we will do it, we haven't done it yet as APIs are evolving, I think for the next big iteration where we'll introduce the data types APIs is a good moment to start publishing the docs.
